import { QuizQuestion } from '../quiz-types';

export const exploringQuestions: QuizQuestion[] = [
  {
    id: 'trip-type',
    title: 'Trip Type',
    question: 'What type of safari experience are you looking for?',
    type: 'single',
    required: true,
    options: [
      {
        id: 'adventure',
        value: 'adventure',
        label: 'Adventure Safari',
        description: 'Active experiences with hiking, walking safaris, and off-road adventures',
        icon: 'Compass',
        nudge: 'Perfect for thrill-seekers who want to get close to nature',
      },
      {
        id: 'luxury',
        value: 'luxury',
        label: 'Luxury Safari',
        description: 'Premium accommodations with exceptional service and comfort',
        icon: 'Star',
        nudge: 'Ideal for those who want comfort without compromising on wildlife experiences',
      },
      {
        id: 'cultural',
        value: 'cultural',
        label: 'Cultural Safari',
        description: 'Immersive experiences with local communities and traditions',
        icon: 'Users',
        nudge: 'Great for travelers interested in authentic cultural exchanges',
      },
      {
        id: 'wildlife',
        value: 'wildlife',
        label: 'Wildlife Focus',
        description: 'Dedicated game viewing with expert guides and photography opportunities',
        icon: 'Camera',
        nudge: 'Perfect for wildlife enthusiasts and photographers',
      },
    ],
  },
  {
    id: 'safari-style',
    title: 'Safari Style',
    question: 'How do you prefer to experience your safari?',
    type: 'single',
    required: true,
    options: [
      {
        id: 'game-drives',
        value: 'game-drives',
        label: 'Classic Game Drives',
        description: 'Traditional vehicle-based safari experiences',
        icon: 'Compass',
        nudge: 'The most popular way to see wildlife comfortably',
      },
      {
        id: 'walking-safari',
        value: 'walking-safari',
        label: 'Walking Safaris',
        description: 'On-foot exploration with experienced guides',
        icon: 'Users',
        nudge: 'Get closer to nature and learn about smaller details',
      },
      {
        id: 'mixed-activities',
        value: 'mixed-activities',
        label: 'Mixed Activities',
        description: 'Combination of drives, walks, and other activities',
        icon: 'Star',
        nudge: 'Best of both worlds for varied experiences',
      },
      {
        id: 'specialized',
        value: 'specialized',
        label: 'Specialized Safari',
        description: 'Photography, birding, or research-focused trips',
        icon: 'Camera',
        nudge: 'Perfect for specific interests and expertise development',
      },
    ],
  },
  {
    id: 'experience-level',
    title: 'Experience Level',
    question: "What's your safari experience level?",
    type: 'single',
    required: true,
    options: [
      {
        id: 'first-time',
        value: 'first-time',
        label: 'First-time Safari',
        description: 'This will be my first African safari experience',
        icon: 'Lightbulb',
        nudge: "We'll recommend classic destinations perfect for beginners",
      },
      {
        id: 'some-experience',
        value: 'some-experience',
        label: 'Some Experience',
        description: "I've been on 1-2 safaris before",
        icon: 'Star',
        nudge: 'Ready to explore new destinations and experiences',
      },
      {
        id: 'experienced',
        value: 'experienced',
        label: 'Experienced Safari-goer',
        description: "I've been on multiple safaris and know what I like",
        icon: 'Users',
        nudge: 'We can suggest unique and off-the-beaten-path experiences',
      },
      {
        id: 'expert',
        value: 'expert',
        label: 'Safari Expert',
        description: "I'm very experienced and looking for something special",
        icon: 'Compass',
        nudge: "Let's find you exclusive and extraordinary safari experiences",
      },
    ],
  },
  {
    id: 'comfort-budget',
    title: 'Comfort & Budget',
    question: 'What level of comfort and service do you prefer?',
    type: 'single',
    required: true,
    options: [
      {
        id: 'budget-friendly',
        value: 'budget-friendly',
        label: 'Budget-Friendly',
        description: 'Basic accommodations, shared facilities, great value',
        icon: 'DollarSign',
        nudge: 'Perfect for adventurous travelers who prioritize experiences over luxury',
      },
      {
        id: 'mid-range',
        value: 'mid-range',
        label: 'Mid-Range Comfort',
        description: 'Comfortable lodges with good amenities and service',
        icon: 'Heart',
        nudge: 'Great balance of comfort and value for most travelers',
      },
      {
        id: 'luxury',
        value: 'luxury',
        label: 'Luxury Experience',
        description: 'High-end lodges with exceptional service and amenities',
        icon: 'Star',
        nudge: 'Indulge in premium comfort while experiencing wildlife',
      },
      {
        id: 'ultra-luxury',
        value: 'ultra-luxury',
        label: 'Ultra-Luxury',
        description: 'Exclusive camps with personalized service and unique experiences',
        icon: 'Users',
        nudge: 'The ultimate in safari luxury and exclusivity',
      },
    ],
  },
  {
    id: 'priorities',
    title: 'Priorities',
    question: 'What are your main priorities for this safari? (Select all that apply)',
    type: 'multiple',
    required: true,
    options: [
      {
        id: 'big-five',
        value: 'big-five',
        label: 'See the Big Five',
        description: 'Lion, leopard, elephant, buffalo, and rhino',
        icon: 'Star',
        nudge: 'Classic safari goal - we know the best spots',
      },
      {
        id: 'photography',
        value: 'photography',
        label: 'Photography',
        description: 'Capture amazing wildlife and landscape photos',
        icon: 'Camera',
        nudge: "We'll recommend the best light and positioning for shots",
      },
      {
        id: 'relaxation',
        value: 'relaxation',
        label: 'Relaxation',
        description: 'Unwind and disconnect from daily stress',
        icon: 'Heart',
        nudge: "Perfect for rejuvenating in nature's tranquility",
      },
      {
        id: 'education',
        value: 'education',
        label: 'Learning & Education',
        description: 'Learn about wildlife, conservation, and ecosystems',
        icon: 'Lightbulb',
        nudge: 'Great for curious minds who want to understand nature',
      },
      {
        id: 'adventure',
        value: 'adventure',
        label: 'Adventure Activities',
        description: 'Hiking, walking safaris, and active experiences',
        icon: 'Compass',
        nudge: 'Perfect for active travelers seeking excitement',
      },
      {
        id: 'cultural',
        value: 'cultural',
        label: 'Cultural Experiences',
        description: 'Meet local communities and learn about traditions',
        icon: 'Users',
        nudge: 'Enrich your journey with authentic cultural connections',
      },
    ],
  },
];

export const exploringStageInfo = {
  id: 'exploring',
  title: 'Exploring',
  description: 'Discover your safari style and preferences',
  icon: 'Compass',
  duration: '3-5 min',
  totalQuestions: exploringQuestions.length,
};
