import { QuizQuestion } from '../quiz-types';

export const narrowingQuestions: QuizQuestion[] = [
  {
    id: 'preferred-countries',
    title: 'Preferred Countries',
    question: 'Which African countries interest you most? (Select all that apply)',
    type: 'multiple',
    required: true,
    options: [
      {
        id: 'kenya',
        value: 'kenya',
        label: 'Kenya',
        description: 'Masai Mara, diverse landscapes, Great Migration',
        icon: 'Compass',
        nudge: 'Home to the world-famous Masai Mara and incredible wildlife diversity',
      },
      {
        id: 'tanzania',
        value: 'tanzania',
        label: 'Tanzania',
        description: 'Serengeti, Ngorongoro Crater, Mount Kilimanjaro',
        icon: 'Star',
        nudge: 'Features the iconic Serengeti and breathtaking Ngorongoro Crater',
      },
      {
        id: 'south-africa',
        value: 'south-africa',
        label: 'South Africa',
        description: 'Kruger National Park, wine regions, diverse experiences',
        icon: 'Heart',
        nudge: 'Perfect blend of wildlife, culture, and modern amenities',
      },
      {
        id: 'botswana',
        value: 'botswana',
        label: 'Botswana',
        description: 'Okavango Delta, exclusive experiences, pristine wilderness',
        icon: 'Users',
        nudge: "Offers some of Africa's most exclusive and pristine safari experiences",
      },
      {
        id: 'namibia',
        value: 'namibia',
        label: 'Namibia',
        description: 'Desert landscapes, unique wildlife, dramatic scenery',
        icon: 'Camera',
        nudge: 'Stunning desert landscapes and unique desert-adapted wildlife',
      },
      {
        id: 'zambia',
        value: 'zambia',
        label: 'Zambia',
        description: 'South Luangwa, walking safaris, authentic experiences',
        icon: 'Lightbulb',
        nudge: 'Birthplace of the walking safari with authentic bush experiences',
      },
      {
        id: 'zimbabwe',
        value: 'zimbabwe',
        label: 'Zimbabwe',
        description: 'Victoria Falls, Hwange National Park, rich history',
        icon: 'Compass',
        nudge: 'Home to magnificent Victoria Falls and excellent wildlife viewing',
      },
      {
        id: 'open-to-suggestions',
        value: 'open-to-suggestions',
        label: 'Open to Suggestions',
        description: "I'm flexible and want expert recommendations",
        icon: 'Star',
        nudge: 'Let our experts recommend the perfect destination for you',
      },
    ],
  },
  {
    id: 'wildlife-interests',
    title: 'Wildlife Interests',
    question: 'Which wildlife experiences are most important to you? (Select all that apply)',
    type: 'multiple',
    required: true,
    options: [
      {
        id: 'big-cats',
        value: 'big-cats',
        label: 'Big Cats',
        description: 'Lions, leopards, cheetahs in their natural habitat',
        icon: 'Star',
        nudge: "Witness the power and grace of Africa's apex predators",
      },
      {
        id: 'elephants',
        value: 'elephants',
        label: 'Elephants',
        description: 'Large herds and intimate elephant encounters',
        icon: 'Heart',
        nudge: 'Experience the intelligence and majesty of these gentle giants',
      },
      {
        id: 'great-migration',
        value: 'great-migration',
        label: 'Great Migration',
        description: 'Wildebeest migration and river crossings',
        icon: 'Compass',
        nudge: "One of nature's greatest spectacles - timing is everything",
      },
      {
        id: 'rhinos',
        value: 'rhinos',
        label: 'Rhinos',
        description: 'Both black and white rhino encounters',
        icon: 'Users',
        nudge: 'See these magnificent endangered species in protected areas',
      },
      {
        id: 'primates',
        value: 'primates',
        label: 'Primates',
        description: 'Gorillas, chimpanzees, and other primates',
        icon: 'Lightbulb',
        nudge: 'Incredible encounters with our closest relatives in the animal kingdom',
      },
      {
        id: 'birds',
        value: 'birds',
        label: 'Birdwatching',
        description: 'Diverse bird species and specialized birding',
        icon: 'Camera',
        nudge: "Africa hosts over 2,000 bird species - a birder's paradise",
      },
      {
        id: 'marine-life',
        value: 'marine-life',
        label: 'Marine Life',
        description: 'Coastal safaris with whale watching and marine experiences',
        icon: 'Heart',
        nudge: 'Combine land and sea for a complete African experience',
      },
      {
        id: 'general-wildlife',
        value: 'general-wildlife',
        label: 'General Wildlife',
        description: 'Overall wildlife diversity and ecosystem experiences',
        icon: 'Star',
        nudge: 'Enjoy the full spectrum of African wildlife in their ecosystems',
      },
    ],
  },
  {
    id: 'landscape-preferences',
    title: 'Landscape Preferences',
    question: 'What types of landscapes appeal to you most? (Select all that apply)',
    type: 'multiple',
    required: true,
    options: [
      {
        id: 'savanna',
        value: 'savanna',
        label: 'Open Savanna',
        description: 'Classic African plains with acacia trees',
        icon: 'Compass',
        nudge: 'The iconic African landscape perfect for game viewing',
      },
      {
        id: 'forest',
        value: 'forest',
        label: 'Forest & Woodland',
        description: 'Dense forests and woodland areas',
        icon: 'Users',
        nudge: 'Rich biodiversity and unique wildlife in forested environments',
      },
      {
        id: 'desert',
        value: 'desert',
        label: 'Desert & Arid',
        description: 'Desert landscapes and arid regions',
        icon: 'Star',
        nudge: 'Dramatic landscapes with specially adapted wildlife',
      },
      {
        id: 'wetlands',
        value: 'wetlands',
        label: 'Wetlands & Delta',
        description: 'River deltas, swamps, and water-rich areas',
        icon: 'Heart',
        nudge: 'Incredible bird life and unique water-based safari experiences',
      },
      {
        id: 'mountains',
        value: 'mountains',
        label: 'Mountains & Highlands',
        description: 'Mountainous regions and highland areas',
        icon: 'Camera',
        nudge: 'Stunning vistas and unique high-altitude wildlife',
      },
      {
        id: 'coastal',
        value: 'coastal',
        label: 'Coastal Areas',
        description: 'Ocean coastlines and beach environments',
        icon: 'Lightbulb',
        nudge: 'Combine safari with beautiful beaches and marine life',
      },
    ],
  },
  {
    id: 'cultural-experiences',
    title: 'Cultural Experiences',
    question: 'How important are cultural interactions during your safari?',
    type: 'single',
    required: true,
    options: [
      {
        id: 'very-important',
        value: 'very-important',
        label: 'Very Important',
        description: 'I want significant cultural interactions and community visits',
        icon: 'Users',
        nudge: "We'll include authentic cultural experiences and community visits",
      },
      {
        id: 'somewhat-important',
        value: 'somewhat-important',
        label: 'Somewhat Important',
        description: "I'd like some cultural experiences but wildlife is priority",
        icon: 'Heart',
        nudge: 'Perfect balance of wildlife and cultural encounters',
      },
      {
        id: 'minimal',
        value: 'minimal',
        label: 'Minimal Interest',
        description: 'I prefer to focus primarily on wildlife and nature',
        icon: 'Star',
        nudge: "We'll focus on pure wildlife experiences with minimal cultural elements",
      },
      {
        id: 'not-interested',
        value: 'not-interested',
        label: 'Not Interested',
        description: 'I want to focus exclusively on wildlife and landscapes',
        icon: 'Camera',
        nudge: 'Pure wildlife focus with no cultural components',
      },
    ],
  },
  {
    id: 'accommodation-style',
    title: 'Accommodation Style',
    question: 'What type of accommodation appeals to you most?',
    type: 'single',
    required: true,
    options: [
      {
        id: 'luxury-lodges',
        value: 'luxury-lodges',
        label: 'Luxury Lodges',
        description: 'High-end permanent lodges with full amenities',
        icon: 'Star',
        nudge: 'Maximum comfort and service in beautiful settings',
      },
      {
        id: 'tented-camps',
        value: 'tented-camps',
        label: 'Tented Camps',
        description: 'Comfortable canvas tents with good facilities',
        icon: 'Compass',
        nudge: 'Classic safari atmosphere with modern comfort',
      },
      {
        id: 'mobile-camping',
        value: 'mobile-camping',
        label: 'Mobile Camping',
        description: 'Moving camps that follow wildlife movements',
        icon: 'Users',
        nudge: 'Ultimate flexibility to be where the action is',
      },
      {
        id: 'eco-lodges',
        value: 'eco-lodges',
        label: 'Eco-Lodges',
        description: 'Environmentally sustainable accommodations',
        icon: 'Heart',
        nudge: 'Responsible tourism with minimal environmental impact',
      },
      {
        id: 'mixed-accommodation',
        value: 'mixed-accommodation',
        label: 'Mixed Accommodation',
        description: 'Combination of different accommodation types',
        icon: 'Lightbulb',
        nudge: 'Experience variety in your accommodation styles',
      },
    ],
  },
];

export const narrowingStageInfo = {
  id: 'narrowing',
  title: 'Narrowing',
  description: 'Choose your ideal destinations and experiences',
  icon: 'Users',
  duration: '4-6 min',
  totalQuestions: narrowingQuestions.length,
};
