import { QuizQuestion } from '../quiz-types';

export const timingQuestions: QuizQuestion[] = [
  {
    id: 'budget-range',
    title: 'Budget Range',
    question: "What's your approximate budget per person for this safari?",
    type: 'single',
    required: true,
    options: [
      {
        id: 'budget-under-3k',
        value: 'under-3000',
        label: 'Under $3,000',
        description: 'Budget-friendly options with basic accommodations',
        icon: 'DollarSign',
        nudge: 'Great value safaris with authentic experiences',
      },
      {
        id: 'budget-3k-5k',
        value: '3000-5000',
        label: '$3,000 - $5,000',
        description: 'Mid-range comfort with good amenities',
        icon: 'Heart',
        nudge: 'Perfect balance of comfort and value for most travelers',
      },
      {
        id: 'budget-5k-8k',
        value: '5000-8000',
        label: '$5,000 - $8,000',
        description: 'Premium experiences with luxury touches',
        icon: 'Star',
        nudge: 'High-quality accommodations and exclusive experiences',
      },
      {
        id: 'budget-8k-12k',
        value: '8000-12000',
        label: '$8,000 - $12,000',
        description: 'Luxury safaris with exceptional service',
        icon: 'Users',
        nudge: 'Top-tier luxury with personalized service and unique experiences',
      },
      {
        id: 'budget-over-12k',
        value: 'over-12000',
        label: 'Over $12,000',
        description: 'Ultra-luxury and exclusive private experiences',
        icon: 'Camera',
        nudge: 'The ultimate in safari luxury and exclusivity',
      },
      {
        id: 'budget-flexible',
        value: 'flexible',
        label: 'Flexible Budget',
        description: 'I want to see options across different price ranges',
        icon: 'Lightbulb',
        nudge: "We'll show you the best value at different price points",
      },
    ],
  },
  {
    id: 'travel-months',
    title: 'Travel Timing',
    question: 'When would you prefer to travel? (Select all that apply)',
    type: 'multiple',
    required: true,
    options: [
      {
        id: 'jan-feb',
        value: 'january-february',
        label: 'January - February',
        description: 'Dry season, excellent game viewing, calving season',
        icon: 'Star',
        nudge: 'Peak season with excellent weather and wildlife activity',
      },
      {
        id: 'mar-may',
        value: 'march-may',
        label: 'March - May',
        description: 'Green season, fewer crowds, great for photography',
        icon: 'Camera',
        nudge: 'Beautiful landscapes and excellent value with fewer tourists',
      },
      {
        id: 'jun-aug',
        value: 'june-august',
        label: 'June - August',
        description: 'Dry season, Great Migration, peak wildlife viewing',
        icon: 'Compass',
        nudge: 'Prime time for the Great Migration and excellent game viewing',
      },
      {
        id: 'sep-nov',
        value: 'september-november',
        label: 'September - November',
        description: 'Shoulder season, good weather, moderate crowds',
        icon: 'Heart',
        nudge: 'Great balance of good weather and reasonable prices',
      },
      {
        id: 'dec',
        value: 'december',
        label: 'December',
        description: 'Holiday season, green landscapes, active wildlife',
        icon: 'Users',
        nudge: 'Festive season with lush landscapes and active wildlife',
      },
      {
        id: 'flexible-timing',
        value: 'flexible',
        label: 'Flexible Timing',
        description: 'I can travel anytime and want the best recommendations',
        icon: 'Lightbulb',
        nudge: "We'll recommend the optimal timing for your preferences",
      },
    ],
  },
  {
    id: 'trip-duration',
    title: 'Trip Duration',
    question: 'How long would you like your safari to be?',
    type: 'single',
    required: true,
    options: [
      {
        id: 'short-3-5-days',
        value: '3-5-days',
        label: '3-5 Days',
        description: 'Quick safari getaway, perfect for first-timers',
        icon: 'Clock',
        nudge: 'Perfect introduction to safari with key highlights',
      },
      {
        id: 'week-6-8-days',
        value: '6-8-days',
        label: '6-8 Days',
        description: 'Classic safari length, good variety of experiences',
        icon: 'Star',
        nudge: 'Most popular duration allowing for diverse experiences',
      },
      {
        id: 'extended-9-12-days',
        value: '9-12-days',
        label: '9-12 Days',
        description: 'Extended safari with multiple destinations',
        icon: 'Compass',
        nudge: 'Comprehensive safari covering multiple parks and regions',
      },
      {
        id: 'long-2-weeks-plus',
        value: '2-weeks-plus',
        label: '2+ Weeks',
        description: 'Ultimate safari adventure across multiple countries',
        icon: 'Users',
        nudge: 'Epic journey covering the best of East or Southern Africa',
      },
      {
        id: 'flexible-duration',
        value: 'flexible',
        label: 'Flexible Duration',
        description: "I'm open to recommendations based on the best experiences",
        icon: 'Heart',
        nudge: "We'll recommend the ideal duration for your chosen experiences",
      },
    ],
  },
  {
    id: 'group-size',
    title: 'Group Size',
    question: 'How many people will be traveling?',
    type: 'single',
    required: true,
    options: [
      {
        id: 'solo',
        value: 'solo',
        label: 'Solo Traveler',
        description: 'Just me - looking for solo-friendly options',
        icon: 'Users',
        nudge: "We'll find great solo options or small group opportunities",
      },
      {
        id: 'couple',
        value: 'couple',
        label: 'Couple (2 people)',
        description: 'Romantic safari for two',
        icon: 'Heart',
        nudge: 'Perfect for intimate experiences and romantic settings',
      },
      {
        id: 'small-group-3-4',
        value: 'small-group-3-4',
        label: 'Small Group (3-4 people)',
        description: 'Family or close friends',
        icon: 'Users',
        nudge: 'Ideal size for personalized experiences and flexibility',
      },
      {
        id: 'medium-group-5-8',
        value: 'medium-group-5-8',
        label: 'Medium Group (5-8 people)',
        description: 'Extended family or friend group',
        icon: 'Star',
        nudge: 'Great for shared experiences and group dynamics',
      },
      {
        id: 'large-group-9-plus',
        value: 'large-group-9-plus',
        label: 'Large Group (9+ people)',
        description: 'Big family reunion or celebration group',
        icon: 'Compass',
        nudge: 'Special arrangements for large groups and celebrations',
      },
    ],
  },
  {
    id: 'booking-timeline',
    title: 'Booking Timeline',
    question: 'When are you looking to book and travel?',
    type: 'single',
    required: true,
    options: [
      {
        id: 'asap',
        value: 'asap',
        label: 'ASAP (Next 3 months)',
        description: 'I want to travel as soon as possible',
        icon: 'Clock',
        nudge: "We'll focus on immediately available options",
      },
      {
        id: 'next-6-months',
        value: 'next-6-months',
        label: 'Next 6 Months',
        description: 'Planning for travel within 6 months',
        icon: 'Star',
        nudge: 'Good planning window for optimal availability and pricing',
      },
      {
        id: 'next-year',
        value: 'next-year',
        label: 'Next 6-12 Months',
        description: 'Planning ahead for next year',
        icon: 'Heart',
        nudge: 'Perfect timing for planning and securing the best options',
      },
      {
        id: 'future-planning',
        value: 'future-planning',
        label: 'Future Planning (1+ years)',
        description: 'Long-term planning for a future trip',
        icon: 'Lightbulb',
        nudge: 'Excellent for planning special occasions and dream trips',
      },
      {
        id: 'just-exploring',
        value: 'just-exploring',
        label: 'Just Exploring',
        description: "I'm researching and gathering information",
        icon: 'Camera',
        nudge: 'Perfect time to explore options and get inspired',
      },
    ],
  },
  {
    id: 'flexibility',
    title: 'Flexibility',
    question: 'How flexible are you with your travel plans?',
    type: 'single',
    required: true,
    options: [
      {
        id: 'very-flexible',
        value: 'very-flexible',
        label: 'Very Flexible',
        description: 'I can adjust dates, destinations, and plans for better deals',
        icon: 'Heart',
        nudge: 'Great! Flexibility often leads to better experiences and value',
      },
      {
        id: 'somewhat-flexible',
        value: 'somewhat-flexible',
        label: 'Somewhat Flexible',
        description: 'I have some flexibility with dates and minor plan changes',
        icon: 'Star',
        nudge: 'Good balance of planning and adaptability',
      },
      {
        id: 'limited-flexibility',
        value: 'limited-flexibility',
        label: 'Limited Flexibility',
        description: 'I have specific requirements and limited ability to change',
        icon: 'Clock',
        nudge: "We'll work within your specific requirements",
      },
      {
        id: 'fixed-plans',
        value: 'fixed-plans',
        label: 'Fixed Plans',
        description: 'I have very specific dates and requirements',
        icon: 'Users',
        nudge: "We'll find the best options within your exact specifications",
      },
    ],
  },
];

export const timingStageInfo = {
  id: 'timing',
  title: 'Timing',
  description: 'Plan your budget, schedule, and booking details',
  icon: 'Clock',
  duration: '3-4 min',
  totalQuestions: timingQuestions.length,
};
